id: bash_script
learningObjectives: 
- Writing bash scripts
hints:
- To get arguments in your bash script you can use the following [link](https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script)
- It's always a good idea to make sure you don't have any redundant characters (including spaces or \n). 
- In order to allow someone else to use your script you would want to make it exectutable. You can find instructions here [link](https://www.andrewcbancroft.com/blog/musings/make-bash-script-executable/)
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Since we're doing this over and over almost every week, it would be nice if we can save it as a script in our repo so others will be able to use it too"
        delay: 1300
      - text: "Please create a new script under the backend directory called `extract_names.sh` (and make sure you have the permission to run it)"
        delay: 1300
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Lovely. Let me take a look.
              
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Amazing, that will save us tons of work.
              
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Umm… something is not quite right, please make sure your output is in the following format: `first name` `last name`.

        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    testFile: check.sh
