id: bash_extract_names
learningObjectives: 
- Manipulating strings and cutting out parts of a file
hints:
- Make sure the first name comes before the last name, maybe there is a command to flip them?
- It's easier to see the result when you et rid of the text you don't actually need
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hi, can you please tell me their actual names? As in: first name + last name. Thanks"
        delay: 1500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - Brad Pertrew
            - Amjad Halil
            - Ken Hatake
            - Elisabeth Perl
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "Thanks $[user.name}" 
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: "I need only their names. First name and then last name."
              delay: 2500
