id: funneldrop_reproduce_locally
learningObjectives: 
- Reproducing a bug locally 
hints:
- All modern web browsers can show you what your website looks like on mobile, so
  you'll be able to easily debug and develop for mobile. You can use the developer
  tools to see it.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Now that we know which users are affected, go ahead and fix the bug!"
        delay: 1300
      - text: "Only, you know, don’t—you might break something"
        delay: 1400
      - text: "It’s not that I don’t trust you, but the management definitely doesn’t, so please begin by **reproducing the bug locally** and sending me the **URL of the path** where you saw the issue. Then we’ll try to fix it on your machine, and only if it works, we’ll fix it in production."
        delay: 3500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:      
          - actionId: github_pr_comment
            params:
              person: head-of-rd
              message: Lovely. Let me take a look.
              
        github_pr_workflow_complete_success:
          do:
          - actionId: github_pr_approve
            params:
              person: head-of-rd
              message: Amazing, that will save us tons of work.
              
        github_pr_workflow_complete_failure:
          do:
          - actionId: github_pr_reject
            params:
              person: head-of-rd
              message: Umm… something is not quite right, please take another look and try again.

        github_pr_merged:
          do:
          - actionId: finish_step


githubActions:
  backend:
    testFile: check.sh
